# self.data_map = {"pr": 2, "ni": 3, "virt": 4, "res":5, "shr": 6, "cpu": 8, "mem": 9}

-
  file_path: &FILEPATH D:/work/auto-performance/data/top.txt
  filter:
    pid: 789
  calculate: &CALCULATE
    - cpu: custom
-
  file_path: *FILEPATH
  filter:
    pid: 789
  calculate: *CALCULATE
    
  
