sampler:
  settings:
    path: ./temp
  tasks:
    - name: top-cpus
      command:
        command: adb shell "top -p 274,831,5576 -b -n 60 -d 1"
        settings:
          status: False
          times: 60
          delay: 1
          cut: True
