sampler:
  path: ./temp
  name: demo
  tags:
    - 'top'
    - 'meminfo'
  commands:
    - 'adb shell "top -p 2272 -b -n 1"'
    - 'adb shell "dumpsys meminfo 2272"'
  times: 60
  delay: 1
  cut: True
